Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -51,18 +51,6 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKER_REPO }}/my-nginx:latest
 
-      - name: Copy docker-compose.yml to EC2
-        env:
-          SSH_KEY: ${{ secrets.SSH_KEY }}
-          SSH_HOST: ${{ secrets.SSH_HOST }}
-        run: |
-          # Save SSH private key to a file
-          echo "$SSH_KEY" > /tmp/id_rsa
-          chmod 600 /tmp/id_rsa
-
-          # Copy docker-compose.yml to the server, overwrite if exists
-          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa docker-compose.yml ec2-user@$SSH_HOST:/home/ec2-user/docker-compose.yml
-
       - name: Deploy to EC2
         env:
           SSH_KEY: ${{ secrets.SSH_KEY }}
@@ -71,21 +59,32 @@ jobs:
           # Save SSH private key to a file
           echo "$SSH_KEY" > /tmp/id_rsa
           chmod 600 /tmp/id_rsa
-        
-          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@$SSH_HOST << EOF
+
+          # Copy docker-compose.yml and nginx.conf to the server, overwrite if exists
+          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa docker-compose.yml ec2-user@$SSH_HOST:/home/ec2-user/docker-compose.yml
+          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa ./hoopifront/nginx/nginx.conf ec2-user@$SSH_HOST:/home/ec2-user/nginx.conf
+
+          # SSH into the server, move the nginx.conf to the correct location, and restart Nginx
+          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ec2-user@$SSH_HOST << 'EOF'
+            sudo mv /home/ec2-user/nginx.conf /etc/nginx/nginx.conf
+            sudo systemctl restart nginx
+
             cd /home/ec2-user
             docker-compose down
             docker-compose pull
+            docker-compose up -d
 
-            # Try to start the services, retrying if necessary
+            # Check the health status of the nginx container
             for i in {1..5}; do
-              docker-compose up -d && break || sleep 10
+              if [ "$(docker inspect -f '{{.State.Health.Status}}' ec2-user_nginx_1)" == "healthy" ]; then
+                echo "Nginx container is healthy."
+                exit 0
+              fi
+              echo "Waiting for Nginx container to become healthy..."
+              sleep 10
             done
 
-            # Check the logs of the nginx container if it's unhealthy
-            if [ "$(docker inspect -f '{{.State.Health.Status}}' ec2-user_nginx_1)" != "healthy" ]; then
-              echo "Nginx container logs:"
-              docker logs ec2-user_nginx_1
-              exit 1
-            fi
+            echo "Nginx container failed to become healthy."
+            docker logs ec2-user_nginx_1
+            exit 1
           EOF
